title: Lara San Juan # your name (or website title) here
logo: "/images/lara3.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello, I'm Lara! 
  <br><br>
  An aspiring data scientist with a Bachelor's degree in Maths & Economics (Joint Honours) from the University of York and over 7 years of experience in the Financial Services industry.
  <br><br>
  More About Me
  <br><br>
  I began learning how to code at the start of 2021 and I was immediately hooked. Since then, I completed a 12-week Data Science Bootcamp with the Developer Academy, part of which I completed whilst working full time as a Financial Planning Analyst. At the end of 2021, I decided to commit to Data Science and dedicate myself to full time learning.
  <br><br>
  <a href="https://www.linkedin.com/in/lara-san-juan-9b139698/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
