title: Lara San Juan # your name (or website title) here
logo: "/images/lara3.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello, I'm Lara! 
  <br><br>
  An aspiring data scientist with a Bachelor's degree in Maths & Economics from the University of York and 7 years of experience in the Financial Services industry as a Financial Planning Analyst
  <br><br>
  <a href="https://www.linkedin.com/in/lara-san-juan-9b139698/">View My LinkedIn Profile</a> 



<br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
